Documentation Workflow Fixes
netascode/ansible-dc-vxlan-example pull request #12
Opened 2024-06-11 23:02 UTC by mikewiebe

This PR fixes a few issues with the workflow to setup a working environment

2024-06-11 23:51 UTC, mtarking requested changes

2024-06-11 23:51 UTC, mtarking commented on README.md
> +To simplify the usage of the collection we are providing you with an [example repository](https://github.com/netascode/ansible-dc-vxlan-example) that you can clone from github which creates the prope
Capitalize GitHub and update sentence to maybe something like this:

```that you can clone from GitHub which creates the proper skeleton structure required```

2024-06-11 23:51 UTC, mtarking commented on README.md
> +In this directory you will now create the new virtual environment and install a python version of your choice. At the _time of this writting_, a commonly used version is python version 3.10.13.  Comm
Capitalize Python in two places

2024-06-11 23:51 UTC, mtarking commented on README.md
> +This repository is designed to build the skeleton for the Network as Code DC VXLAN Ansible Galaxy collection. Cloaning this repository will create a working structure that you can build upon to autom
Should Collection be capitalized?

2024-06-11 23:51 UTC, mtarking commented on README.md
> +This repository is designed to build the skeleton for the Network as Code DC VXLAN Ansible Galaxy collection. Cloaning this repository will create a working structure that you can build upon to autom
...using Nexus Dashboard Fabric Controller (NDFC).

2024-06-11 23:51 UTC, mtarking commented on README.md
> +This sets the correct path for all the python modules and libraries in the virtual environment that was created. If you look in that directory you will find the collections package locations. Here is
Caps Python

2024-06-11 23:51 UTC, mtarking commented on README.md
> +This sets the correct path for all the python modules and libraries in the virtual environment that was created. If you look in that directory you will find the collections package locations. Here is
This should be ```collections_path```

2024-06-11 23:52 UTC, rafmuller approved these changes

2024-06-11 23:56 UTC, rafmuller approved these changes

2024-06-11 23:58 UTC, rafmuller approved these changes

2024-06-12 13:37 UTC, mtarking approved these changes

2024-06-12 13:37 UTC, merged